apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io  
spec:
  project: default

  source:
    repoURL: https://github.com/r3hnny/argo-works.git
    targetRevision: HEAD
    path: fr-nanaj/app01
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

#    automated:
#      selfHeal: true
#      prune: true